modLoader="javafml" 
loaderVersion="[36,)"
license="MIT"
[[mods]]
modId="fem"
version="${file.jarVersion}" 
displayName="ekfarmod" 
logoFile="examplemod.png" 
credits="created by ekfar and zutkm and layker" 
description='''
         |
         |/
        /|
       / |
      /_|/
        /|
       / |
      /_|
'''

[[dependencies.fem]]
    modId="forge"
    mandatory=true 
    versionRange="[36,)" 
    ordering="NONE"
    side="BOTH"
# Here's another dependency
[[dependencies.fem]]
    modId="minecraft"
    mandatory=true
    versionRange="[1.16.5,1.17)"
    ordering="NONE"
    side="BOTH"
